type_name: Correct CI compilation for antique clang (llvm < 3.6.2)
Since I found no reliable way to identify clang older version
for AppleClang and the standard clang, I had to resort to a trick inside
`.travis.yml`

* .travis.yml defines _HANA_DISABLE_CONSTEXPR_TYPE_NAME
for xcode6.4 (supports end in January 2019 on travis), and
for clang version 3.5.0-4ubuntu2~trusty2

* When this is defined, type_name_compiler_capabilities.hpp will
not define _HANA_TN_CAN_CONSTEXPR

See faulty travis logs here:

https://travis-ci.org/pthom/hana/jobs/470452243#L4920
/home/travis/build/pthom/hana/test/experimental/type_name_stringliteral_test.cpp:51:5: error: static_assert expression is not an integral constant expression
    RUN_ONE_TYPE_TEST_COMPILE_TIME(void, "void");
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/pthom/hana/test/experimental/type_name_stringliteral_test.cpp:14:13: note: expanded from macro 'RUN_ONE_TYPE_TEST_COMPILE_TIME'
            type_name_details::stringliteral_equal_sz(                              \
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/travis/build/pthom/hana/include/boost/hana/experimental/detail/type_name_stringliteral.hpp:49:17: note: subexpression not valid in a constant expression
            if (cs1.ptr[idx] != cs2.ptr[idx])
/home/travis/build/pthom/hana/include/boost/hana/experimental/detail/type_name_stringliteral.hpp:57:16: note: in call to 'stringliteral_equal(type_name_details::type_name_impl_stringliteral<void>(), { literal, constexpr_strlen(literal) })'
        return stringliteral_equal(

https://travis-ci.org/pthom/hana/jobs/470452243#L6504
/home/travis/build/pthom/hana/include/boost/hana/experimental/type_name.hpp:25:40: error: non-type template argument is not a constant expression
            return boost::hana::string<*(name.ptr + i)...>{};
                                       ^
/home/travis/build/pthom/hana/include/boost/hana/experimental/type_name.hpp:42:39: note: in instantiation of function template specialization 'boost::hana::experimental::type_name_details::type_name_impl<void, 0, 1, 2, 3>' requested here
            return type_name_details::type_name_impl<T>(std::make_index_sequence<name.length>{});